theme: jekyll-theme-minimal
title: Tejas Morkar
description: Android and Web Developer | Interested in Machine Learning & Data Science | Currently working working on GANs | <br> <br> [Download My Resume](https://drive.google.com/file/d/1g4NCb5Hgef4EAZTAg5w_Lf0x3GvP-Zes/view?usp=sharing)
logo: https://avatars3.githubusercontent.com/u/35477326?s=460&u=c1368375704aa1115ed95c49847fb6bc38e343d1&v=4
google_analytics: UA-155126859-2
